/*     */ package org.controlsfx.glyphfont;
/*     */ 
/*     */ import java.io.InputStream;
/*     */ import java.util.Arrays;
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ public class FontAwesome
/*     */   extends GlyphFont
/*     */ {
/*  76 */   private static String fontName = "FontAwesome";
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public enum Glyph
/*     */     implements INamedCharacter
/*     */   {
/*  84 */     ADJUST(''),
/*  85 */     ADN(''),
/*  86 */     ALIGN_CENTER(''),
/*  87 */     ALIGN_JUSTIFY(''),
/*  88 */     ALIGN_LEFT(''),
/*  89 */     ALIGN_RIGHT(''),
/*  90 */     AMBULANCE(''),
/*  91 */     ANCHOR(''),
/*  92 */     ANDROID(''),
/*  93 */     ANGELLIST(''),
/*  94 */     ANGLE_DOUBLE_DOWN(''),
/*  95 */     ANGLE_DOUBLE_LEFT(''),
/*  96 */     ANGLE_DOUBLE_RIGHT(''),
/*  97 */     ANGLE_DOUBLE_UP(''),
/*  98 */     ANGLE_DOWN(''),
/*  99 */     ANGLE_LEFT(''),
/* 100 */     ANGLE_RIGHT(''),
/* 101 */     ANGLE_UP(''),
/* 102 */     APPLE(''),
/* 103 */     ARCHIVE(''),
/* 104 */     AREA_CHART(''),
/* 105 */     ARROW_CIRCLE_DOWN(''),
/* 106 */     ARROW_CIRCLE_LEFT(''),
/* 107 */     ARROW_CIRCLE_O_DOWN(''),
/* 108 */     ARROW_CIRCLE_O_LEFT(''),
/* 109 */     ARROW_CIRCLE_O_RIGHT(''),
/* 110 */     ARROW_CIRCLE_O_UP(''),
/* 111 */     ARROW_CIRCLE_RIGHT(''),
/* 112 */     ARROW_CIRCLE_UP(''),
/* 113 */     ARROW_DOWN(''),
/* 114 */     ARROW_LEFT(''),
/* 115 */     ARROW_RIGHT(''),
/* 116 */     ARROW_UP(''),
/* 117 */     ARROWS(''),
/* 118 */     ARROWS_ALT(''),
/* 119 */     ARROWS_H(''),
/* 120 */     ARROWS_V(''),
/* 121 */     ASTERISK(''),
/* 122 */     AT(''),
/* 123 */     AUTOMOBILE(''),
/* 124 */     BACKWARD(''),
/* 125 */     BAN(''),
/* 126 */     BANK(''),
/* 127 */     BAR_CHART(''),
/* 128 */     BAR_CHART_O(''),
/* 129 */     BARCODE(''),
/* 130 */     BARS(''),
/* 131 */     BED(''),
/* 132 */     BEER(''),
/* 133 */     BEHANCE(''),
/* 134 */     BEHANCE_SQUARE(''),
/* 135 */     BELL(''),
/* 136 */     BELL_O(''),
/* 137 */     BELL_SLASH(''),
/* 138 */     BELL_SLASH_O(''),
/* 139 */     BICYCLE(''),
/* 140 */     BINOCULARS(''),
/* 141 */     BIRTHDAY_CAKE(''),
/* 142 */     BITBUCKET(''),
/* 143 */     BITBUCKET_SQUARE(''),
/* 144 */     BITCOIN(''),
/* 145 */     BOLD(''),
/* 146 */     BOLT(''),
/* 147 */     BOMB(''),
/* 148 */     BOOK(''),
/* 149 */     BOOKMARK(''),
/* 150 */     BOOKMARK_ALT(''),
/* 151 */     BRIEFCASE(''),
/* 152 */     BTC(''),
/* 153 */     BUG(''),
/* 154 */     BUILDING(''),
/* 155 */     BUILDING_ALT(''),
/* 156 */     BULLHORN(''),
/* 157 */     BULLSEYE(''),
/* 158 */     BUS(''),
/* 159 */     BUYSELLADS(''),
/* 160 */     CAB(''),
/* 161 */     CALCULATOR(''),
/* 162 */     CALENDAR(''),
/* 163 */     CALENDAR_ALT(''),
/* 164 */     CAMERA(''),
/* 165 */     CAMERA_RETRO(''),
/* 166 */     CAR(''),
/* 167 */     CARET_DOWN(''),
/* 168 */     CARET_LEFT(''),
/* 169 */     CARET_RIGHT(''),
/* 170 */     CARET_SQUARE_ALT_DOWN(''),
/* 171 */     CARET_SQUARE_ALT_LEFT(''),
/* 172 */     CARET_SQUARE_ALT_RIGHT(''),
/* 173 */     CARET_SQUARE_ALT_UP(''),
/* 174 */     CARET_UP(''),
/* 175 */     CART_ARROW_DOWN(''),
/* 176 */     CART_PLUS(''),
/* 177 */     CC(''),
/* 178 */     CC_AMEX(''),
/* 179 */     CC_DISCOVER(''),
/* 180 */     CC_MASTERCARD(''),
/* 181 */     CC_PAYPAL(''),
/* 182 */     CC_STRIPE(''),
/* 183 */     CC_VISA(''),
/* 184 */     CERTIFICATE(''),
/* 185 */     CHAIN(''),
/* 186 */     CHAIN_BROKEN(''),
/* 187 */     CHECK(''),
/* 188 */     CHECK_CIRCLE(''),
/* 189 */     CHECK_CIRCLE_ALT(''),
/* 190 */     CHECK_SQUARE(''),
/* 191 */     CHECK_SQUARE_ALT(''),
/* 192 */     CHEVRON_CIRCLE_DOWN(''),
/* 193 */     CHEVRON_CIRCLE_LEFT(''),
/* 194 */     CHEVRON_CIRCLE_RIGHT(''),
/* 195 */     CHEVRON_CIRCLE_UP(''),
/* 196 */     CHEVRON_DOWN(''),
/* 197 */     CHEVRON_LEFT(''),
/* 198 */     CHEVRON_RIGHT(''),
/* 199 */     CHEVRON_UP(''),
/* 200 */     CHILD(''),
/* 201 */     CIRCLE(''),
/* 202 */     CIRCLE_ALT(''),
/* 203 */     CIRCLE_ALT_NOTCH(''),
/* 204 */     CIRCLE_THIN(''),
/* 205 */     CLIPBOARD(''),
/* 206 */     CLOCK_ALT(''),
/* 207 */     CLOSE(''),
/* 208 */     CLOUD(''),
/* 209 */     CLOUD_DOWNLOAD(''),
/* 210 */     CLOUD_UPLOAD(''),
/* 211 */     CNY(''),
/* 212 */     CODE(''),
/* 213 */     CODE_FORK(''),
/* 214 */     CODEPEN(''),
/* 215 */     COFFEE(''),
/* 216 */     COG(''),
/* 217 */     COGS(''),
/* 218 */     COLUMNS(''),
/* 219 */     COMMENT(''),
/* 220 */     COMMENT_ALT(''),
/* 221 */     COMMENTS(''),
/* 222 */     COMMENTS_ALT(''),
/* 223 */     COMPASS(''),
/* 224 */     COMPRESS(''),
/* 225 */     CONNECTDEVELOP(''),
/* 226 */     COPY(''),
/* 227 */     COPYRIGHT(''),
/* 228 */     CREDIT_CARD(''),
/* 229 */     CROP(''),
/* 230 */     CROSSHAIRS(''),
/* 231 */     CSS3(''),
/* 232 */     CUBE(''),
/* 233 */     CUBES(''),
/* 234 */     CUT(''),
/* 235 */     CUTLERY(''),
/* 236 */     DASHBOARD(''),
/* 237 */     DASHCUBE(''),
/* 238 */     DATABASE(''),
/* 239 */     DEDENT(''),
/* 240 */     DELICIOUS(''),
/* 241 */     DESKTOP(''),
/* 242 */     DEVIANTART(''),
/* 243 */     DIAMOND(''),
/* 244 */     DIGG(''),
/* 245 */     DOLLAR(''),
/* 246 */     DOT_CIRCLE_ALT(''),
/* 247 */     DOWNLOAD(''),
/* 248 */     DRIBBBLE(''),
/* 249 */     DROPBOX(''),
/* 250 */     DRUPAL(''),
/* 251 */     EDIT(''),
/* 252 */     EJECT(''),
/* 253 */     ELLIPSIS_H(''),
/* 254 */     ELLIPSIS_V(''),
/* 255 */     EMPIRE(''),
/* 256 */     ENVELOPE(''),
/* 257 */     ENVELOPE_ALT(''),
/* 258 */     ENVELOPE_SQUARE(''),
/* 259 */     ERASER(''),
/* 260 */     EUR(''),
/* 261 */     EURO(''),
/* 262 */     EXCHANGE(''),
/* 263 */     EXCLAMATION(''),
/* 264 */     EXCLAMATION_CIRCLE(''),
/* 265 */     EXCLAMATION_TRIANGLE(''),
/* 266 */     EXPAND(''),
/* 267 */     EXTERNAL_LINK(''),
/* 268 */     EXTERNAL_LINK_SQUARE(''),
/* 269 */     EYE(''),
/* 270 */     EYE_SLASH(''),
/* 271 */     EYEDROPPER(''),
/* 272 */     FACEBOOK(''),
/* 273 */     FACEBOOK_F(''),
/* 274 */     FACEBOOK_ALTFFICIAL(''),
/* 275 */     FACEBOOK_SQUARE(''),
/* 276 */     FAST_BACKWARD(''),
/* 277 */     FAST_FORWARD(''),
/* 278 */     FAX(''),
/* 279 */     FEMALE(''),
/* 280 */     FIGHTER_JET(''),
/* 281 */     FILE(''),
/* 282 */     FILE_ARCHIVE_ALT(''),
/* 283 */     FILE_AUDIO_ALT(''),
/* 284 */     FILE_CODE_ALT(''),
/* 285 */     FILE_EXCEL_ALT(''),
/* 286 */     FILE_IMAGE_ALT(''),
/* 287 */     FILE_MOVIE_ALT(''),
/* 288 */     FILE_ALT(''),
/* 289 */     FILE_PDF_ALT(''),
/* 290 */     FILE_PHOTO_ALT(''),
/* 291 */     FILE_PICTURE_ALT(''),
/* 292 */     FILE_POWERPOINT_ALT(''),
/* 293 */     FILE_SOUND_ALT(''),
/* 294 */     FILE_TEXT(''),
/* 295 */     FILE_TEXT_ALT(''),
/* 296 */     FILE_VIDEO_ALT(''),
/* 297 */     FILE_WORD_ALT(''),
/* 298 */     FILE_ZIP_ALT(''),
/* 299 */     FILES_ALT(''),
/* 300 */     FILM(''),
/* 301 */     FILTER(''),
/* 302 */     FIRE(''),
/* 303 */     FIRE_EXTINGUISHER(''),
/* 304 */     FLAG(''),
/* 305 */     FLAG_CHECKERED(''),
/* 306 */     FLAG_ALT(''),
/* 307 */     FLASH(''),
/* 308 */     FLASK(''),
/* 309 */     FLICKR(''),
/* 310 */     FLOPPY_ALT(''),
/* 311 */     FOLDER(''),
/* 312 */     FOLDER_ALT(''),
/* 313 */     FOLDER_OPEN(''),
/* 314 */     FOLDER_OPEN_ALT(''),
/* 315 */     FONT(''),
/* 316 */     FORUMBEE(''),
/* 317 */     FORWARD(''),
/* 318 */     FOURSQUARE(''),
/* 319 */     FROWN_ALT(''),
/* 320 */     FUTBOL_ALT(''),
/* 321 */     GAMEPAD(''),
/* 322 */     GAVEL(''),
/* 323 */     GBP(''),
/* 324 */     GE(''),
/* 325 */     GEAR(''),
/* 326 */     GEARS(''),
/* 327 */     GENDERLESS(''),
/* 328 */     GIFT(''),
/* 329 */     GIT(''),
/* 330 */     GIT_SQUARE(''),
/* 331 */     GITHUB(''),
/* 332 */     GITHUB_ALT(''),
/* 333 */     GITHUB_SQUARE(''),
/* 334 */     GITTIP(''),
/* 335 */     GLASS(''),
/* 336 */     GLOBE(''),
/* 337 */     GOOGLE(''),
/* 338 */     GOOGLE_PLUS(''),
/* 339 */     GOOGLE_PLUS_SQUARE(''),
/* 340 */     GOOGLE_WALLET(''),
/* 341 */     GRADUATION_CAP(''),
/* 342 */     GRATIPAY(''),
/* 343 */     GROUP(''),
/* 344 */     H_SQUARE(''),
/* 345 */     HACKER_NEWS(''),
/* 346 */     HAND_ALT_DOWN(''),
/* 347 */     HAND_ALT_LEFT(''),
/* 348 */     HAND_ALT_RIGHT(''),
/* 349 */     HAND_ALT_UP(''),
/* 350 */     HDD_ALT(''),
/* 351 */     HEADER(''),
/* 352 */     HEADPHONES(''),
/* 353 */     HEART(''),
/* 354 */     HEART_ALT(''),
/* 355 */     HEARTBEAT(''),
/* 356 */     HISTORY(''),
/* 357 */     HOME(''),
/* 358 */     HOSPITAL_ALT(''),
/* 359 */     HOTEL(''),
/* 360 */     HTML5(''),
/* 361 */     ILS(''),
/* 362 */     IMAGE(''),
/* 363 */     INBOX(''),
/* 364 */     INDENT(''),
/* 365 */     INFO(''),
/* 366 */     INFO_CIRCLE(''),
/* 367 */     INR(''),
/* 368 */     INSTAGRAM(''),
/* 369 */     INSTITUTION(''),
/* 370 */     IOXHOST(''),
/* 371 */     ITALIC(''),
/* 372 */     JOOMLA(''),
/* 373 */     JPY(''),
/* 374 */     JSFIDDLE(''),
/* 375 */     KEY(''),
/* 376 */     KEYBOARD_ALT(''),
/* 377 */     KRW(''),
/* 378 */     LANGUAGE(''),
/* 379 */     LAPTOP(''),
/* 380 */     LASTFM(''),
/* 381 */     LASTFM_SQUARE(''),
/* 382 */     LEAF(''),
/* 383 */     LEANPUB(''),
/* 384 */     LEGAL(''),
/* 385 */     LEMON_ALT(''),
/* 386 */     LEVEL_DOWN(''),
/* 387 */     LEVEL_UP(''),
/* 388 */     LIFE_BOUY(''),
/* 389 */     LIFE_BUOY(''),
/* 390 */     LIFE_RING(''),
/* 391 */     LIFE_SAVER(''),
/* 392 */     LIGHTBULB_ALT(''),
/* 393 */     LINE_CHART(''),
/* 394 */     LINK(''),
/* 395 */     LINKEDIN(''),
/* 396 */     LINKEDIN_SQUARE(''),
/* 397 */     LINUX(''),
/* 398 */     LIST(''),
/* 399 */     LIST_ALT(''),
/* 400 */     LIST_OL(''),
/* 401 */     LIST_UL(''),
/* 402 */     LOCATION_ARROW(''),
/* 403 */     LOCK(''),
/* 404 */     LONG_ARROW_DOWN(''),
/* 405 */     LONG_ARROW_LEFT(''),
/* 406 */     LONG_ARROW_RIGHT(''),
/* 407 */     LONG_ARROW_UP(''),
/* 408 */     MAGIC(''),
/* 409 */     MAGNET(''),
/* 410 */     MAIL_FORWARD(''),
/* 411 */     MAIL_REPLY(''),
/* 412 */     MAIL_REPLY_ALL(''),
/* 413 */     MALE(''),
/* 414 */     MAP_MARKER(''),
/* 415 */     MARS(''),
/* 416 */     MARS_DOUBLE(''),
/* 417 */     MARS_STROKE(''),
/* 418 */     MARS_STROKE_H(''),
/* 419 */     MARS_STROKE_V(''),
/* 420 */     MAXCDN(''),
/* 421 */     MEANPATH(''),
/* 422 */     MEDIUM(''),
/* 423 */     MEDKIT(''),
/* 424 */     MEH_ALT(''),
/* 425 */     MERCURY(''),
/* 426 */     MICROPHONE(''),
/* 427 */     MICROPHONE_SLASH(''),
/* 428 */     MINUS(''),
/* 429 */     MINUS_CIRCLE(''),
/* 430 */     MINUS_SQUARE(''),
/* 431 */     MINUS_SQUARE_ALT(''),
/* 432 */     MOBILE(''),
/* 433 */     MOBILE_PHONE(''),
/* 434 */     MONEY(''),
/* 435 */     MOON_ALT(''),
/* 436 */     MORTAR_BOARD(''),
/* 437 */     MOTORCYCLE(''),
/* 438 */     MUSIC(''),
/* 439 */     NAVICON(''),
/* 440 */     NEUTER(''),
/* 441 */     NEWSPAPER_ALT(''),
/* 442 */     OPENID(''),
/* 443 */     OUTDENT(''),
/* 444 */     PAGELINES(''),
/* 445 */     PAINT_BRUSH(''),
/* 446 */     PAPER_PLANE(''),
/* 447 */     PAPER_PLANE_ALT(''),
/* 448 */     PAPERCLIP(''),
/* 449 */     PARAGRAPH(''),
/* 450 */     PASTE(''),
/* 451 */     PAUSE(''),
/* 452 */     PAW(''),
/* 453 */     PAYPAL(''),
/* 454 */     PENCIL(''),
/* 455 */     PENCIL_SQUARE(''),
/* 456 */     PENCIL_SQUARE_ALT(''),
/* 457 */     PHONE(''),
/* 458 */     PHONE_SQUARE(''),
/* 459 */     PHOTO(''),
/* 460 */     PICTURE_ALT(''),
/* 461 */     PIE_CHART(''),
/* 462 */     PIED_PIPER(''),
/* 463 */     PIED_PIPER_ALT(''),
/* 464 */     PINTEREST(''),
/* 465 */     PINTEREST_P(''),
/* 466 */     PINTEREST_SQUARE(''),
/* 467 */     PLANE(''),
/* 468 */     PLAY(''),
/* 469 */     PLAY_CIRCLE(''),
/* 470 */     PLAY_CIRCLE_ALT(''),
/* 471 */     PLUG(''),
/* 472 */     PLUS(''),
/* 473 */     PLUS_CIRCLE(''),
/* 474 */     PLUS_SQUARE(''),
/* 475 */     PLUS_SQUARE_ALT(''),
/* 476 */     POWER_OFF(''),
/* 477 */     PRINT(''),
/* 478 */     PUZZLE_PIECE(''),
/* 479 */     QQ(''),
/* 480 */     QRCODE(''),
/* 481 */     QUESTION(''),
/* 482 */     QUESTION_CIRCLE(''),
/* 483 */     QUOTE_LEFT(''),
/* 484 */     QUOTE_RIGHT(''),
/* 485 */     RA(''),
/* 486 */     RANDOM(''),
/* 487 */     REBEL(''),
/* 488 */     RECYCLE(''),
/* 489 */     REDDIT(''),
/* 490 */     REDDIT_SQUARE(''),
/* 491 */     REFRESH(''),
/* 492 */     REMOVE(''),
/* 493 */     RENREN(''),
/* 494 */     REORDER(''),
/* 495 */     REPEAT(''),
/* 496 */     REPLY(''),
/* 497 */     REPLY_ALL(''),
/* 498 */     RETWEET(''),
/* 499 */     RMB(''),
/* 500 */     ROAD(''),
/* 501 */     ROCKET(''),
/* 502 */     ROTATE_LEFT(''),
/* 503 */     ROTATE_RIGHT(''),
/* 504 */     ROUBLE(''),
/* 505 */     RSS(''),
/* 506 */     RSS_SQUARE(''),
/* 507 */     RUB(''),
/* 508 */     RUBLE(''),
/* 509 */     RUPEE(''),
/* 510 */     SAVE(''),
/* 511 */     SCISSORS(''),
/* 512 */     SEARCH(''),
/* 513 */     SEARCH_MINUS(''),
/* 514 */     SEARCH_PLUS(''),
/* 515 */     SELLSY(''),
/* 516 */     SEND(''),
/* 517 */     SEND_ALT(''),
/* 518 */     SERVER(''),
/* 519 */     SHARE(''),
/* 520 */     SHARE_ALT(''),
/* 521 */     SHARE_ALT_SQUARE(''),
/* 522 */     SHARE_SQUARE(''),
/* 523 */     SHARE_SQUARE_ALT(''),
/* 524 */     SHEKEL(''),
/* 525 */     SHEQEL(''),
/* 526 */     SHIELD(''),
/* 527 */     SHIP(''),
/* 528 */     SHIRTSINBULK(''),
/* 529 */     SHOPPING_CART(''),
/* 530 */     SIGN_IN(''),
/* 531 */     SIGN_OUT(''),
/* 532 */     SIGNAL(''),
/* 533 */     SIMPLYBUILT(''),
/* 534 */     SITEMAP(''),
/* 535 */     SKYATLAS(''),
/* 536 */     SKYPE(''),
/* 537 */     SLACK(''),
/* 538 */     SLIDERS(''),
/* 539 */     SLIDESHARE(''),
/* 540 */     SMILE_ALT(''),
/* 541 */     SOCCER_BALL_ALT(''),
/* 542 */     SORT(''),
/* 543 */     SORT_ALPHA_ASC(''),
/* 544 */     SORT_ALPHA_DESC(''),
/* 545 */     SORT_AMOUNT_ASC(''),
/* 546 */     SORT_AMOUNT_DESC(''),
/* 547 */     SORT_ASC(''),
/* 548 */     SORT_DESC(''),
/* 549 */     SORT_DOWN(''),
/* 550 */     SORT_NUMERIC_ASC(''),
/* 551 */     SORT_NUMERIC_DESC(''),
/* 552 */     SORT_UP(''),
/* 553 */     SOUNDCLOUD(''),
/* 554 */     SPACE_SHUTTLE(''),
/* 555 */     SPINNER(''),
/* 556 */     SPOON(''),
/* 557 */     SPOTIFY(''),
/* 558 */     SQUARE(''),
/* 559 */     SQUARE_ALT(''),
/* 560 */     STACK_EXCHANGE(''),
/* 561 */     STACK_OVERFLOW(''),
/* 562 */     STAR(''),
/* 563 */     STAR_HALF(''),
/* 564 */     STAR_HALF_EMPTY(''),
/* 565 */     STAR_HALF_FULL(''),
/* 566 */     STAR_HALF_ALT(''),
/* 567 */     STAR_ALT(''),
/* 568 */     STEAM(''),
/* 569 */     STEAM_SQUARE(''),
/* 570 */     STEP_BACKWARD(''),
/* 571 */     STEP_FORWARD(''),
/* 572 */     STETHOSCOPE(''),
/* 573 */     STOP(''),
/* 574 */     STREET_VIEW(''),
/* 575 */     STRIKETHROUGH(''),
/* 576 */     STUMBLEUPON(''),
/* 577 */     STUMBLEUPON_CIRCLE(''),
/* 578 */     SUBSCRIPT(''),
/* 579 */     SUBWAY(''),
/* 580 */     SUITCASE(''),
/* 581 */     SUN_ALT(''),
/* 582 */     SUPERSCRIPT(''),
/* 583 */     SUPPORT(''),
/* 584 */     TABLE(''),
/* 585 */     TABLET(''),
/* 586 */     TACHOMETER(''),
/* 587 */     TAG(''),
/* 588 */     TAGS(''),
/* 589 */     TASKS(''),
/* 590 */     TAXI(''),
/* 591 */     TENCENT_WEIBO(''),
/* 592 */     TERMINAL(''),
/* 593 */     TEXT_HEIGHT(''),
/* 594 */     TEXT_WIDTH(''),
/* 595 */     TH(''),
/* 596 */     TH_LARGE(''),
/* 597 */     TH_LIST(''),
/* 598 */     THUMB_TACK(''),
/* 599 */     THUMBS_DOWN(''),
/* 600 */     THUMBS_ALT_DOWN(''),
/* 601 */     THUMBS_ALT_UP(''),
/* 602 */     THUMBS_UP(''),
/* 603 */     TICKET(''),
/* 604 */     TIMES(''),
/* 605 */     TIMES_CIRCLE(''),
/* 606 */     TIMES_CIRCLE_ALT(''),
/* 607 */     TINT(''),
/* 608 */     TOGGLE_DOWN(''),
/* 609 */     TOGGLE_LEFT(''),
/* 610 */     TOGGLE_OFF(''),
/* 611 */     TOGGLE_ON(''),
/* 612 */     TOGGLE_RIGHT(''),
/* 613 */     TOGGLE_UP(''),
/* 614 */     TRAIN(''),
/* 615 */     TRANSGENDER(''),
/* 616 */     TRANSGENDER_ALT(''),
/* 617 */     TRASH(''),
/* 618 */     TRASH_ALT(''),
/* 619 */     TREE(''),
/* 620 */     TRELLO(''),
/* 621 */     TROPHY(''),
/* 622 */     TRUCK(''),
/* 623 */     TRY(''),
/* 624 */     TTY(''),
/* 625 */     TUMBLR(''),
/* 626 */     TUMBLR_SQUARE(''),
/* 627 */     TURKISH_LIRA(''),
/* 628 */     TWITCH(''),
/* 629 */     TWITTER(''),
/* 630 */     TWITTER_SQUARE(''),
/* 631 */     UMBRELLA(''),
/* 632 */     UNDERLINE(''),
/* 633 */     UNDO(''),
/* 634 */     UNIVERSITY(''),
/* 635 */     UNLINK(''),
/* 636 */     UNLOCK(''),
/* 637 */     UNLOCK_ALT(''),
/* 638 */     UNSORTED(''),
/* 639 */     UPLOAD(''),
/* 640 */     USD(''),
/* 641 */     USER(''),
/* 642 */     USER_MD(''),
/* 643 */     USER_PLUS(''),
/* 644 */     USER_SECRET(''),
/* 645 */     USER_TIMES(''),
/* 646 */     USERS(''),
/* 647 */     VENUS(''),
/* 648 */     VENUS_DOUBLE(''),
/* 649 */     VENUS_MARS(''),
/* 650 */     VIACOIN(''),
/* 651 */     VIDEO_CAMERA(''),
/* 652 */     VIMEO_SQUARE(''),
/* 653 */     VINE(''),
/* 654 */     VK(''),
/* 655 */     VOLUME_DOWN(''),
/* 656 */     VOLUME_OFF(''),
/* 657 */     VOLUME_UP(''),
/* 658 */     WARNING(''),
/* 659 */     WECHAT(''),
/* 660 */     WEIBO(''),
/* 661 */     WEIXIN(''),
/* 662 */     WHATSAPP(''),
/* 663 */     WHEELCHAIR(''),
/* 664 */     WIFI(''),
/* 665 */     WINDOWS(''),
/* 666 */     WON(''),
/* 667 */     WORDPRESS(''),
/* 668 */     WRENCH(''),
/* 669 */     XING(''),
/* 670 */     XING_SQUARE(''),
/* 671 */     YAHOO(''),
/* 672 */     YELP(''),
/* 673 */     YEN(''),
/* 674 */     YOUTUBE(''),
/* 675 */     YOUTUBE_PLAY(''),
/* 676 */     YOUTUBE_SQUARE('');
/*     */ 
/*     */ 
/*     */     
/*     */     private final char ch;
/*     */ 
/*     */ 
/*     */     
/*     */     Glyph(char ch) {
/* 685 */       this.ch = ch;
/*     */     }
/*     */ 
/*     */     
/*     */     public char getChar() {
/* 690 */       return this.ch;
/*     */     }
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public FontAwesome() {
/* 702 */     this(FontAwesome.class.getResourceAsStream("fontawesome-webfont.ttf"));
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public FontAwesome(String url) {
/* 710 */     super(fontName, 14, url, true);
/* 711 */     registerAll(Arrays.asList((INamedCharacter[])Glyph.values()));
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public FontAwesome(InputStream is) {
/* 719 */     super(fontName, 14, is, true);
/* 720 */     registerAll(Arrays.asList((INamedCharacter[])Glyph.values()));
/*     */   }
/*     */ }


/* Location:              C:\Users\leo\Desktop\server.jar!\org\controlsfx\glyphfont\FontAwesome.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */